spring.application.name=Proyecto Java EE

server.port=8080
server.servlet.context-path=/kioscobyf

spring.datasource.url = jdbc:postgresql://localhost:5432/proyectokiosco
spring.datasource.username = ${DB_USER}
spring.datasource.password = ${DB_PASS}
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true


